In [1]:
import pandas as pd

In [2]:
file_csv="National_Custom_Data.csv"

mortality_df=pd.read_csv(file_csv)

In [3]:
mortality_df.head(15)

,AREA,SUB AREA,AGE GROUP,SEASON,WEEK,THRESHOLD,BASELINE,PERCENT P&I,NUM INFLUENZA DEATHS,NUM PNEUMONIA DEATHS,TOTAL DEATHS,PERCENT COMPLETE
0,National,NaN,All,2019-20,40,5.7,5.3,5.2,16,"2,698","52,442",> 100%
1,National,NaN,All,2019-20,41,5.7,5.4,5.3,16,"2,766","52,850",> 100%
2,National,NaN,All,2019-20,42,5.8,5.5,5.5,18,"2,976","54,108",> 100%
3,National,NaN,All,2019-20,43,5.9,5.6,5.6,30,"2,983","53,896",> 100%
4,National,NaN,All,2019-20,44,6.0,5.7,5.4,31,"2,904","53,953",> 100%
5,National,NaN,All,2019-20,45,6.2,5.8,5.6,31,"3,056","55,435",> 100%
6,National,NaN,All,2019-20,46,6.3,5.9,5.6,39,"3,089","55,651",> 100%
7,National,NaN,All,2019-20,47,6.4,6.0,5.4,50,"2,988","55,938",> 100%
8,National,NaN,All,2019-20,48,6.5,6.2,5.5,65,"2,966","55,160",> 100%
9,National,NaN,All,2019-20,49,6.6,6.3,6.0,97,"3,272","56,402",> 100%
10,National,NaN,All,2019-20,50,6.7,6.4,6.2,109,"3,409","56,641",> 100%
11,National,NaN,All,2019-20,51,6.8,6.5,6.1,123,"3,302","56,316",> 100%
12,National,NaN,All,2019-20,52,6.9,6.6,6.3,192,"3,411","57,071",> 100%
13,National,NaN,All,2019-20,1,7.0,6.7,7.4,403,"3,930","58,200",> 100%
14,National,NaN,All,2019-20,2,7.1,6.7,7.5,432,"3,920","58,309",> 100%

In [10]:
mortality_df2=mortality_df.drop(columns=["AGE GROUP","AREA","SUB AREA","THRESHOLD","BASELINE","PERCENT P&I","PERCENT COMPLETE"])

In [11]:
mortality_df2.head()

    SEASON  WEEK NUM INFLUENZA DEATHS NUM PNEUMONIA DEATHS TOTAL DEATHS
0  2019-20    40                   16                2,698       52,442
1  2019-20    41                   16                2,766       52,850
2  2019-20    42                   18                2,976       54,108
3  2019-20    43                   30                2,983       53,896
4  2019-20    44                   31                2,904       53,953

In [12]:
mortality_json=mortality_df2.to_json("mortality_df.json")