In [1]:
import pandas as pd
import json

In [2]:
vac1516="dataView1340_3.xls"
vac1617="dataView2065_3.xls"
vac1718="dataView2164_3.xls"
vac1819="dataView2246_3.xls"

vac1516_df=pd.read_excel(vac1516)
vac1617_df=pd.read_excel(vac1617)
vac1718_df=pd.read_excel(vac1718)
vac1819_df=pd.read_excel(vac1819)

In [3]:
vac1516_df.head(20)
del vac1516_df["Unnamed: 2"]

In [4]:
vac1516_df.head()

cleaned1516=vac1516_df.drop(columns=["Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1516=cleaned1516.drop([0,1],axis=0)
cleaned1516.head()

cleaned1516.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1516.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1516["Unnamed: 47"]
del cleaned1516["Unnamed: 53"]
del cleaned1516["Unnamed: 65"]
del cleaned1516["Unnamed: 71"]


cleaned1516.insert(0, 'Flu Season', '2015-2016')

In [5]:
cleaned1516.tail(20)

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
44,2015-2016,Tennessee,5803,1862,565,782,515,3941,2438,1180,1258,1503
45,2015-2016,Texas,21564,12125,3560,5001,3564,9439,5810,3195,2615,3629
46,2015-2016,Utah,8627,1702,534,610,558,6925,5003,3161,1842,1922
47,2015-2016,Vermont,6678,1964,562,975,427,4714,3191,1480,1711,1523
48,2015-2016,Virginia,9032,2799,901,1263,635,6233,4248,2260,1988,1985
49,2015-2016,Washington,14147,2428,766,1029,633,11719,7380,3705,3675,4339
50,2015-2016,West Virginia,7627,2064,637,920,507,5563,3854,2025,1829,1709
51,2015-2016,Wisconsin,5460,1943,575,850,518,3517,2331,1181,1150,1186
52,2015-2016,Wyoming,5668,1927,546,872,509,3741,2113,902,1211,1628
53,2015-2016,United States,446013,126846,38713,54825,33308,319167,205848,105988,99860,113319
54,2015-2016,Region 1,49661,13850,4054,6633,3163,35811,22790,10702,12088,13021
55,2015-2016,Region 2,30014,7823,2617,3231,1975,22191,14888,7710,7178,7303
56,2015-2016,Region 3,51480,17031,5342,7433,4256,34449,22689,11448,11241,11760
57,2015-2016,Region 4,68401,18152,5625,8112,4415,50249,31883,16498,15385,18366
58,2015-2016,Region 5,53880,14161,4338,5953,3870,39719,26377,13970,12407,13342
59,2015-2016,Region 6,46217,19832,5810,8305,5717,26385,15856,7922,7934,10529
60,2015-2016,Region 7,40993,7713,2316,3229,2168,33280,21363,11084,10279,11917
61,2015-2016,Region 8,44614,11246,3430,4741,3075,33368,21721,11476,10245,11647
62,2015-2016,Region 9,30583,8739,2696,3674,2369,21844,14166,7870,6296,7678
63,2015-2016,Region 10,30170,8299,2485,3514,2300,21871,14115,7308,6807,7756

In [6]:
vac1617_df.head()
cleaned1617=vac1617_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1617=cleaned1617.drop([0,1],axis=0)
cleaned1617.head()

cleaned1617.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1617.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1617["Unnamed: 47"]
del cleaned1617["Unnamed: 53"]
del cleaned1617["Unnamed: 65"]
del cleaned1617["Unnamed: 71"]

cleaned1617.insert(0, 'Flu Season', '2016-2017')

In [7]:
cleaned1617.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2016-2017,Alabama,7901,2555,757,1196,602,5346,3393,1774,1619,1953
3,2016-2017,Alaska,4998,2238,688,971,579,2760,1989,980,1009,771
4,2016-2017,Arizona,11261,2357,706,1030,621,8904,4950,2486,2464,3954
5,2016-2017,Arkansas,6418,2303,691,1027,585,4115,2075,896,1179,2040
6,2016-2017,California,8010,3095,1059,1348,688,4915,3726,2436,1290,1189

In [8]:
vac1718_df.head()
cleaned1718=vac1718_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1718=cleaned1718.drop([0,1],axis=0)
cleaned1718.head()

cleaned1718.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1718.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1718["Unnamed: 47"]
del cleaned1718["Unnamed: 53"]
del cleaned1718["Unnamed: 65"]
del cleaned1718["Unnamed: 71"]

cleaned1718.insert(0, 'Flu Season', '2017-2018')

In [9]:
cleaned1718.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2017-2018,Alabama,7547,2671,854,1224,593,4876,3030,1560,1470,1846
3,2017-2018,Alaska,3690,1752,564,719,469,1938,1311,718,593,627
4,2017-2018,Arizona,12285,2358,740,1120,498,9927,5985,3168,2817,3942
5,2017-2018,Arkansas,6287,2129,647,925,557,4158,2031,909,1122,2127
6,2017-2018,California,10838,2355,809,950,596,8483,6643,4380,2263,1840

In [10]:
vac1819_df.head()
cleaned1819=vac1819_df.drop(columns=["Unnamed: 2","Influenza vaccination (General Population) - Age",
                        "Unnamed: 3","Unnamed: 4","Unnamed: 6","Unnamed: 99","Unnamed: 100","Unnamed: 101","Unnamed: 102","Unnamed: 103","Unnamed: 104",
                        "Unnamed: 105","Unnamed: 106","Unnamed: 7","Unnamed: 8","Unnamed: 9","Unnamed: 10","Unnamed: 12","Unnamed: 13","Unnamed: 14"
                                    ,"Unnamed: 15","Unnamed: 16","Unnamed: 18","Unnamed: 19","Unnamed: 20","Unnamed: 21","Unnamed: 22",
                                    "Unnamed: 24","Unnamed: 25","Unnamed: 26","Unnamed: 27","Unnamed: 28",
                                    "Unnamed: 30","Unnamed: 31","Unnamed: 32","Unnamed: 33","Unnamed: 34",
                                    "Unnamed: 36","Unnamed: 37","Unnamed: 38","Unnamed: 39","Unnamed: 40",
                                    "Unnamed: 42","Unnamed: 43","Unnamed: 44","Unnamed: 45","Unnamed: 46",
                                    "Unnamed: 48","Unnamed: 49","Unnamed: 50","Unnamed: 51","Unnamed: 52",
                                    "Unnamed: 54","Unnamed: 55","Unnamed: 56","Unnamed: 57","Unnamed: 58",
                                    "Unnamed: 91","Unnamed: 92","Unnamed: 93","Unnamed: 94","Unnamed: 95",
                                    "Unnamed: 60","Unnamed: 61","Unnamed: 62","Unnamed: 63","Unnamed: 64",
                                    "Unnamed: 66","Unnamed: 67","Unnamed: 68","Unnamed: 69","Unnamed: 70",
                                    "Unnamed: 72","Unnamed: 73","Unnamed: 74","Unnamed: 75","Unnamed: 76",
                                    "Unnamed: 78","Unnamed: 79","Unnamed: 80","Unnamed: 81","Unnamed: 82",
                                    "Unnamed: 84","Unnamed: 86","Unnamed: 87","Unnamed: 88",
                                    "Unnamed: 89","Unnamed: 90","Unnamed: 96","Unnamed: 97","Unnamed: 98",
                                    "Unnamed: 107","Unnamed: 108", "Influenza vaccination (General Population) - Race/ethnicity"])

cleaned1819=cleaned1819.drop([0,1],axis=0)


cleaned1819.rename(columns={"Unnamed: 0":"Location of Immunization"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 5":"≥ 6 months"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 11":"6 months - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 17":"6 months - 4 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 23":"5 - 12 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 29":"13 - 17 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 35":"≥ 18 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 41":"18 - 64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 59":"18 - 49 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 77":"50 -64 years"},inplace=True)
cleaned1819.rename(columns={"Unnamed: 83":"≥ 65 years"},inplace=True)

del cleaned1819["Unnamed: 47"]
del cleaned1819["Unnamed: 53"]
del cleaned1819["Unnamed: 65"]
del cleaned1819["Unnamed: 71"]

cleaned1819.insert(0, 'Flu Season', '2018-2019')

In [11]:
last10=cleaned1819.tail(10)

last10.head(10
           )

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
54,2018-2019,Region 1,47287,13207,4089,5855,3263,34080,20444,9776,10668,13636
55,2018-2019,Region 2,26785,8308,2924,3509,1875,18477,12114,6642,5472,6363
56,2018-2019,Region 3,55570,21795,7411,10028,4356,33775,21387,11148,10239,12388
57,2018-2019,Region 4,68549,22852,7511,10301,5040,45697,28066,15319,12747,17631
58,2018-2019,Region 5,55393,16318,5324,6990,4004,39075,24966,13599,11367,14109
59,2018-2019,Region 6,45524,21098,7190,7649,6259,24426,15024,8385,6639,9402
60,2018-2019,Region 7,39108,7748,2527,3190,2031,31360,19462,10761,8701,11898
61,2018-2019,Region 8,46072,11625,3857,4907,2861,34447,22057,12613,9444,12390
62,2018-2019,Region 9,30862,9216,3125,3786,2305,21646,14279,8525,5754,7367
63,2018-2019,Region 10,26356,7191,2290,2926,1975,19165,12294,7071,5223,6871

In [12]:
allvacdata=pd.concat([cleaned1516,cleaned1718,cleaned1819])

In [13]:
allvacdata.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
2,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728
3,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652
4,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388
5,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781
6,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702

In [14]:
allvacdata=allvacdata.reset_index(drop=True, inplace=False)

In [15]:
allvacdata.head()

,Flu Season,Location of Immunization,≥ 6 months,6 months - 17 years,6 months - 4 years,5 - 12 years,13 - 17 years,≥ 18 years,18 - 64 years,18 - 49 years,50 -64 years,≥ 65 years
0,2015-2016,Alabama,7822,2375,720,1121,534,5447,3719,1992,1727,1728
1,2015-2016,Alaska,4740,2287,681,955,651,2453,1801,946,855,652
2,2015-2016,Arizona,9739,2418,678,983,757,7321,3933,1859,2074,3388
3,2015-2016,Arkansas,5694,1896,566,797,533,3798,2017,850,1167,1781
4,2015-2016,California,9488,2437,834,1020,583,7051,5349,3452,1897,1702

In [16]:
allvacdata_json=allvacdata.to_json("allvacdata.json")

In [17]:
vacdata_1516=cleaned1516.to_json("vac1516.json")

In [18]:
vacdata_1718=cleaned1718.to_json("vac1718.json")

In [19]:
vacdata_1819=cleaned1819.to_json("vac1819.json")